# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MSTG-JWT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'KeychainSwift', '~> 12.0'

  # Pods for MSTG-JWT

  target 'MSTG-JWTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MSTG-JWTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
